services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /mit/mit-billing/postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - mit-billing-net
    deploy:
      restart_policy:
        condition: any

  backend:
    image: mit-billing-backend:latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      FRONTEND_ORIGIN: http://172.25.164.203:8082
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - mit-billing-net
    ports:
      - target: 8000
        published: 8002
        protocol: tcp
        mode: ingress
    deploy:
      restart_policy:
        condition: any

  frontend:
    image: mit-billing-frontend:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - mit-billing-net
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress
    deploy:
      restart_policy:
        condition: any

networks:
  mit-billing-net:
    driver: overlay
